name: classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas=1.0.3
  - numpy=1.18.4
  - matplotlib=3.2.1
  - seaborn=0.11.0
  - scikit-learn=0.23.1
  - neptune-client
  - psutil
  - pytorch::pytorch=1.6 # -- built from source due to CUDA 11.0 and apex
  - dpkt=1.9.2
  - hmmlearn=0.2.3
  - pytest=5.4.2
  - pytest-mock=3.1.1
  - pyyaml=5.3.1
  - gitpython=3.1.3
  - jupyterlab>=2.1
  - jupytext
  - tqdm
  - ipywidgets
  - nodejs
  - pip:
    - pytorch-lightning==0.8.5
    - nfstream==6.1.3
    - sh==1.13.1
    - pandarallel==1.4.8
    - transformers==3.0.2
    - ngt==1.12.2
