name: classifier
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - jupyterlab>=2.1
  - pandas=1.0.3
  - numpy=1.18.4
  - matplotlib=3.2.1
  - seaborn=0.10.1
  - scikit-learn=0.23.1
  - dpkt=1.9.2
  - hmmlearn=0.2.3
  - imbalanced-learn=0.6.2
  - pytest=5.4.2
  - pytest-mock=3.1.1
  - pyyaml=5.3.1
  - gitpython=3.1.3
  - jupytext
  - tqdm
  - ipywidgets
  - nodejs
  - neptune-client
  - psutil
  - pytorch::pytorch=1.5
  - pytorch::torchvision
  - cudatoolkit=10.2
  - pip:
    - pytorch-lightning
    - nfstream==5.1.5
    - sh==1.13.1
    - pandarallel==1.4.8
